#rules_dir: rules
#output_dir: results
#data_dir: data
rules_dir: workflow/rules
output_dir: workflow/results
data_dir: workflow/data
scripts_dir: workflow/scripts
containers_dir: /home/nnagar/singularity_containers